<?php

namespace AppBundle\Repository;

/**
 * AssignationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignationRepository extends \Doctrine\ORM\EntityRepository
{
}
