<?php

namespace AppBundle\Repository;

/**
 * DechargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DechargeRepository extends \Doctrine\ORM\EntityRepository
{

    public function consultation(
        $agence,
        $statut, 
        $recherche_par, 
        $a_rechercher, 
        $type_date, 
        $mois, 
        $annee, 
        $date_specifique, 
        $debut_date, 
        $fin_date,
        $filtre_motif
    )
    {

        $em = $this->getEntityManager();

        $query = "  select d.id, d.beneficiaire, d.cheque, d.montant, date_format(d.date,'%d/%m/%Y') as date, d.mode_paiement as mode_paiement, m.libelle as service, d.type_motif as motif, date_format(d.mois_facture,'%m/%Y') as mois, date_format(d.date_validation,'%d/%m/%Y') as date_validation, 1 as depense_type, d.virement
                    from decharge d
                    left join motif_decharge m on (d.motif_decharge = m.id)";

        $where = "  where d.statut = " . $statut;
        $where .= "  and d.agence = " . $agence;

        if($recherche_par == 3){
            $where .= " and d.beneficiaire LIKE '%" . $a_rechercher . "%'";
        }

        if ($filtre_motif) {
            $where .= " and m.id = " . $filtre_motif;
        }

        if ($type_date) {
            switch ($type_date) {
                case '1':
                    $now = new \DateTime();
                    $dateNow = $now->format('d-m-Y');
                    $where .= " and date_format(d.date,'%d-%m-%Y') = '" . $dateNow ."'";
                    break;
                
                case '2':
                    $moisAnnee = $mois . "-" . $annee;
                    $where .= " and date_format(d.date,'%m-%Y') = '" . $moisAnnee ."'";
                    break;

                case '3':
                    $where .= " and date_format(d.date,'%Y') = '" . $annee ."'";
                    break;

                case '4':
                    // $date = \DateTime::createFromFormat('j/m/Y', $date_specifique);
                    $where .= " and date_format(d.date,'%d/%m/%Y') = '" . $date_specifique ."'";
                    break;

                case '5':
                    $where .= " and date_format(d.date,'%d/%m/%Y') >= '" . $debut_date ."'";
                    $where .= " and date_format(d.date,'%d/%m/%Y') <= '" . $fin_date ."'";
                    break;

                case '6':
                    $moisAnnee = $mois . "-" . $annee;
                    $where .= " and date_format(d.mois_facture,'%m-%Y') = '" . $moisAnnee ."'";
                    break;
            }
        }

        $where .= " group by d.id";

        $query .= $where;

        $query .= " order by d.id DESC";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;

    }

}
