<?php

namespace AppBundle\Repository;

/**
 * EcheanceAchatDepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcheanceAchatDepenseRepository extends \Doctrine\ORM\EntityRepository
{
}
