<?php

namespace AppBundle\Repository;

/**
 * FactureProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
