<?php

namespace AppBundle\Repository;

/**
 * HistoTypeTacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoTypeTacheRepository extends \Doctrine\ORM\EntityRepository
{
}
