<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

	public function nonAffecteEntrepot($agence)
	{
		$em = $this->getEntityManager();

		// $query = "	select p.id, pe.id as produit_entrepot
		// 			from produit p
		// 			left join produit_entrepot pe on (pe.produit = p.id)
		// 			left join entrepot e on (pe.entrepot = e.id)
		// 			where p.id is not null";

		$query = "	select p.id, pe.id as produit_entrepot
					from produit p
					left join produit_entrepot pe on (pe.produit = p.id)
					left join entrepot e on (pe.entrepot = e.id)
					where (pe.id is null
					or e.id is null)";

		if ($agence) {
			$query .= "	and p.agence = " . $agence ;
		}

		$statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;

	}

	public function getList(
		$agence, 
		$recherche_par = '', 
		$a_rechercher = '',
		$categorie = 0,
		$produit_id = 0
	)
	{
		$em = $this->getEntityManager();
		
		$query = "	select p.id, p.code_produit, p.nom, pe.stock, cp.nom as categorie
					from produit p
					left join categorie_produit cp on (p.categorie_produit = cp.id)
					left join produit_entrepot pe on (pe.produit = p.id)
					where p.nom is not null ";

		if ($agence) {
			$query .= "	and p.agence = " . $agence ;
		}

		if ($recherche_par == 0) { 
			$query .= "	and p.code_produit like '%" . $a_rechercher . "%'";
		}

		if ($recherche_par == 1) {
			$query .= "	and p.nom like '%" . $a_rechercher . "%'";
		}

		if ($categorie) {
			$query .= "	and cp.id = " . $categorie;
		}

		if ($produit_id) {
			$query .= "	and p.id = " . $produit_id;
		}

		$query .= "	and p.is_delete IS NULL";

		$query .= "	order by p.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
	}

	public function notifications(
		$agence, 
		$entrepot = 0
	)
	{
		$em = $this->getEntityManager();
		
		$query = "	select *
					from produit p 
					inner join produit_entrepot pe on (pe.produit = p.id)
					where pe.stock <= pe.stock_alerte";

		if ($agence) {
			$query .= "	and p.agence = " . $agence ;
		}

		$query .= "	order by p.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
	}
}
