<?php

namespace AppBundle\Repository;

/**
 * VariationProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariationProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function list(
        $agence,
        $recherche_par = '',
        $a_rechercher = '',
        $categorie = '',
        $entrepot = 0
    )
    {
        $em = $this->getEntityManager();

        $query = "  select vp.id, p.nom, vp.prix_vente, p.id as produit_id, vp.stock, cp.nom as categorie, (vp.prix_vente * vp.stock) as total, p.code_produit, e.nom as entrepot, pe.indice
                    from variation_produit vp
                    inner join produit_entrepot pe on (vp.produit_entrepot = pe.id)
                    inner join produit p on (pe.produit = p.id)
                    left join entrepot e on (pe.entrepot = e.id)
                    inner join agence ag on (p.agence = ag.id)
                    inner join categorie_produit cp on (p.categorie_produit = cp.id)
                    where vp.stock > 0";

        $query .= " and ag.id = " . $agence;

        if ($entrepot) {
            $query .= " and e.id = " . $entrepot ;
        }

        $query .= " and p.is_delete IS NULL";

        $query .= " order by p.nom ASC";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }

    public function getInfoVariation($id)
    {
        $em = $this->getEntityManager();

        $sql ="SELECT * FROM `variation_produit` WHERE `id` = ? " ;
        $statement = $em->getConnection()->prepare($sql);
        $statement->execute([$id]);
        $result = $statement->fetch();
        return $result ; 
    }
}
